/** All DDRS RBAC roles. */
export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CDSCO_DCGI = 'CDSCO_DCGI',
  CDSCO_ADC = 'CDSCO_ADC',
  CDSCO_REVIEW_OFFICER = 'CDSCO_REVIEW_OFFICER',
  CDSCO_DRUG_INSPECTOR = 'CDSCO_DRUG_INSPECTOR',
  PORT_OFFICER = 'PORT_OFFICER',
  STATE_LICENSING_AUTHORITY = 'STATE_LICENSING_AUTHORITY',
  STATE_DRUG_INSPECTOR = 'STATE_DRUG_INSPECTOR',
  LAB_MANAGER = 'LAB_MANAGER',
  LAB_ANALYST = 'LAB_ANALYST',
  MANUFACTURER = 'MANUFACTURER',
  IMPORTER = 'IMPORTER',
  EXPORTER = 'EXPORTER',
  WHOLESALER_RETAILER = 'WHOLESALER_RETAILER',
  CRO = 'CRO',
  ETHICS_COMMITTEE = 'ETHICS_COMMITTEE',
  BLOOD_CENTRE = 'BLOOD_CENTRE',
  TECHNICAL_PERSON = 'TECHNICAL_PERSON',
  PUBLIC_USER = 'PUBLIC_USER',
}

export const CDSCO_ROLES = [
  Role.CDSCO_DCGI,
  Role.CDSCO_ADC,
  Role.CDSCO_REVIEW_OFFICER,
  Role.CDSCO_DRUG_INSPECTOR,
  Role.PORT_OFFICER,
];

export const STATE_ROLES = [
  Role.STATE_LICENSING_AUTHORITY,
  Role.STATE_DRUG_INSPECTOR,
];

export const LAB_ROLES = [Role.LAB_MANAGER, Role.LAB_ANALYST];

export const INDUSTRY_ROLES = [
  Role.MANUFACTURER,
  Role.IMPORTER,
  Role.EXPORTER,
  Role.WHOLESALER_RETAILER,
  Role.CRO,
  Role.ETHICS_COMMITTEE,
  Role.BLOOD_CENTRE,
  Role.TECHNICAL_PERSON,
];

/** Product categories regulated by CDSCO. */
export enum ProductCategory {
  DRUG = 'DRUG',
  BIOLOGICAL = 'BIOLOGICAL',
  MEDICAL_DEVICE = 'MEDICAL_DEVICE',
  IVD = 'IVD',
  COSMETIC = 'COSMETIC',
  VETERINARY = 'VETERINARY',
  AYUSH = 'AYUSH',
  BLOOD_PRODUCT = 'BLOOD_PRODUCT',
}

/** Regulatory risk class (A/B = State, C/D = Central). */
export enum RiskClass {
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
}

/** Generic application lifecycle states (workflow engine). */
export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PRE_SCREENING = 'PRE_SCREENING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  QUERY_RAISED = 'QUERY_RAISED',
  INSPECTION = 'INSPECTION',
  RECOMMENDED = 'RECOMMENDED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ISSUED = 'ISSUED',
  RENEWED = 'RENEWED',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  SURRENDERED = 'SURRENDERED',
  WITHDRAWN = 'WITHDRAWN',
}

/** Application types covering the full regulatory lifecycle. */
export enum ApplicationType {
  USER_REGISTRATION = 'USER_REGISTRATION',
  SITE_REGISTRATION = 'SITE_REGISTRATION',
  IMPORT_REGISTRATION = 'IMPORT_REGISTRATION',
  MARKET_AUTHORISATION = 'MARKET_AUTHORISATION',
  MANUFACTURING_LICENCE = 'MANUFACTURING_LICENCE',
  IMPORT_LICENCE = 'IMPORT_LICENCE',
  SALE_LICENCE = 'SALE_LICENCE',
  TEST_LICENCE = 'TEST_LICENCE',
  LOAN_LICENCE = 'LOAN_LICENCE',
  RENEWAL = 'RENEWAL',
  ENDORSEMENT = 'ENDORSEMENT',
  POST_APPROVAL_CHANGE = 'POST_APPROVAL_CHANGE',
  SUSPENSION = 'SUSPENSION',
  SURRENDER_CANCELLATION = 'SURRENDER_CANCELLATION',
  WITHDRAWAL = 'WITHDRAWAL',
  CORRECTION = 'CORRECTION',
  APPEAL = 'APPEAL',
  NOC = 'NOC',
  CLINICAL_TRIAL = 'CLINICAL_TRIAL',
}

export enum Jurisdiction {
  CENTRE = 'CENTRE',
  STATE = 'STATE',
  JOINT = 'JOINT',
}

/** Types of regulated entities/organizations in the registry. */
export enum OrganizationType {
  MANUFACTURER = 'MANUFACTURER',
  IMPORTER = 'IMPORTER',
  EXPORTER = 'EXPORTER',
  WHOLESALER = 'WHOLESALER',
  RETAILER = 'RETAILER',
  CRO = 'CRO',
  ETHICS_COMMITTEE = 'ETHICS_COMMITTEE',
  BLOOD_CENTRE = 'BLOOD_CENTRE',
  BA_BE_CENTRE = 'BA_BE_CENTRE',
  CONSULTANT = 'CONSULTANT',
  MARKETER = 'MARKETER',
}

export enum EntityStatus {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum LabType {
  CENTRAL = 'CENTRAL',
  STATE = 'STATE',
  PRIVATE = 'PRIVATE',
}
